version: '3.5'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nest-container
    ports:
      - 3000:3000
    volumes:
      - ./api:/api

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: angular-container
    ports:
      - 4200:4200
    volumes:
      - ./app:/app